;;NOTE: these will be updated as the application is developed

create database mmms-db;

use mmms_db;

CREATE TABLE app_users (
  uid INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(50),
  lastname VARCHAR(50),
  username VARCHAR(50) UNIQUE,
  email VARCHAR(100),
  password VARCHAR(100)
);


INSERT INTO app_users (username, password)
VALUES ('username', '{bcrypt}$2a$10$o0gMlstVvzaG0Jh0HdD4ueczbpUIDdjR3XbC7i/shlGESn1pveRWu');
